---
title: "DescribeThisDataset"
output: html_document
params:
  Dataset: NULL
  Individual: TRUE
  HeadOfDataset: FALSE
  StructureOfDataset: FALSE
  PathOutputFolder: ""
  NameOutputFile: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## `r deparse(substitute(Dataset))`

```{r first, echo=FALSE}
  Dataset= params$Dataset
  Individual= params$Individual
  HeadOfDataset= params$HeadOfDataset
  StructureOfDataset= params$StructureOfDataset
  PathOutputFolder= params$PathOutputFolder
  NameOutputFile= params$NameOutputFile
  
  ## Datatable
  if(!is.data.table(Dataset)){
    Dataset=data.table(Dataset)
  }
  
  ## Name output
  if(NameOutputFile==""){
    NameOutputFile=paste0("Description_of_",deparse(substitute(Dataset)))
  }
  
  ## Directory
  if(PathOutputFolder==""){
    thisdir<-setwd(dirname(rstudioapi::getSourceEditorContext()$path))
    thisdir<-setwd(dirname(rstudioapi::getSourceEditorContext()$path))
    PathOutputFolder=paste0(thisdir,"/g_describeHTML")
  }
  diroutput<-paste0(PathOutputFolder,"/",NameOutputFile,".html")
  
  ## Create folders
  suppressWarnings(if (!file.exists(PathOutputFolder)) dir.create(file.path( PathOutputFolder)))
  
  ## Dimension of the dataset
  Database_dim<-dim(Dataset)
  n_of_observations<-Database_dim[1]
  n_of_variables<-Database_dim[2]
  ## Table Output
  row_of_df_output=4
  df_output<- data.frame(matrix(ncol = n_of_variables, nrow = row_of_df_output))
  colnames(df_output)<-names(Dataset)
  rownames(df_output)<-c("missing_count", "missing_percent", "unique_count", "unique_rate")
  
  for( i in names(Dataset)){
    df_output[1,i]=sum(is.na(Dataset[,get(i)]))
    df_output[2,i]=round((sum(is.na(Dataset[,get(i)]))/n_of_observations)*100, 2)
    df_output[3,i]=length(unique(Dataset[,get(i)]))
    df_output[4,i]=round(length(unique(Dataset[,get(i)]))/n_of_observations, 2)
  }
```

This is a description of `r deparse(substitute(Dataset))`. The dataset is composed by `r n_of_observations` observations of  `r n_of_variables` variables.

```{r DF_output, include=TRUE, echo=FALSE}
knitr::kable(df_output)
```
 
`r if(HeadOfDataset){"This is the head of the dataset"}`

```{r Head, include=TRUE, echo=FALSE}
  ## Head
  if(HeadOfDataset==TRUE){
    knitr::kable(head(Dataset))
  }
```

`r if(StructureOfDataset){"This is the structure of the dataset"}`

```{r Structure, include=TRUE, echo=FALSE}
  ## Structure
  if(StructureOfDataset){
    str(Dataset)
  }
```
 

